routes/auth.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for, flash, session, g
import pymysql, os
from werkzeug.security import check_password_hash
from dotenv import load_dotenv
from os.path import join, dirname
load_dotenv(join(dirname(__file__), '.env'))

auth = Blueprint('auth', __name__)

def get_conn():
    if "conn" not in g:
        g.conn = pymysql.connect(
            host=os.getenv('FLASK_DATABASE_HOST'),
            user=os.getenv('FLASK_DATABASE_USER'),
            password=os.getenv('FLASK_DATABASE_PASSWORD'),
            database=os.getenv('FLASK_DATABASE')
        )
        g.cur=g.conn.cursor()
    return g.conn, g.cur

@auth.route('/login_', methods=['POST', 'GET'])
def login_():
    

    if request.method == 'POST':
       
        username=request.form['username']
        conn, cur = get_conn()
        cur=conn.cursor()
        
        cur.execute("SELECT contraseña, nmrol FROM covid.usuarios, covid.rol WHERE Usuario = '"+username+"' AND rol.idrol = usuarios.rol;")        
        myresult = cur.fetchall()

        cur.close()
        pw="0"
        if myresult:
            pw=myresult[0][0]
            rol=myresult[0][1]
      
        # check if user exists and password is correct
        if username and check_password_hash(pw, request.form['password']):

            session['rol'] = rol
            
            if rol == 'Administrador':
                return redirect(url_for('admin_.register_'))

            elif rol == 'Medico':
                return redirect(url_for('med.medico_choice'))

            elif rol == 'Ayudante':
                return redirect(url_for('helper.choice'))

            else:
                return redirect(url_for('auth.login_'))
        else:
            flash("Username or password invalid")
            return redirect(url_for('auth.login_'))
    else:
        return render_template("login.html")

@auth.route('/logout')
@auth.route('/<rol>/logout')
def logout(rol):
    session.pop('username', None)
    return redirect(url_for('auth.login_'))

routes/med.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for, flash, session,g, jsonify
import pymysql, os
from werkzeug.security import generate_password_hash, check_password_hash
from dotenv import load_dotenv
from os.path import join, dirname
load_dotenv(join(dirname(__file__), '.env'))

med = Blueprint('med', __name__)

def get_conn():
    if "conn" not in g:
        g.conn = pymysql.connect(
            host=os.getenv('FLASK_DATABASE_HOST'),
            user=os.getenv('FLASK_DATABASE_USER'),
            password=os.getenv('FLASK_DATABASE_PASSWORD'),
            database=os.getenv('FLASK_DATABASE')
        )
        g.cur=g.conn.cursor()
    return g.conn, g.cur

@med.route('/medico/choice', methods=['POST', 'GET'])
def medico_choice():
    return render_template("doc_choices.html")
    
@med.route('/ubic', methods=['POST', 'GET'])
def ubic():
    cedula = request.args.get("param1")

    conn, cur = get_conn()
    cur=conn.cursor()
    cur.execute("SELECT regis.latitudCasa, regis.longitudCasa, regis.latitudJob, regis.longitudJob FROM covid.registrar regis where regis.cedula='"+cedula+"' and idCaso = (select MAX(idCaso) FROM covid.registrar regis where regis.cedula='"+cedula+"');")        
    myresult = cur.fetchall()
    cur.close()
    return jsonify(myresult)

@med.route('/medico/search', methods=['POST', 'GET'])
def medico_search():
    if request.method == 'POST':
        search=request.form['search']
       
        select=request.form['select']
        conn, cur = get_conn()
        cur=conn.cursor()
        
        if select == "2":
            cur.execute("SELECT  regis.nombre, regis.apellido, regis.cedula, sex.nmsexo Sexo, regis.nacimiento 'Fecha Nacimiento', regis.dirCasa 'Dirección Casa', regis.dirTrabajo 'Dirección Trabajo', nmresultado 'Resultado Test Covid', regis.fechaExam 'Fecha de Prueba Covid'FROM covid.registrar regis, covid.sexo sex, covid.resultado res WHERE regis.sexo = sex.idsexo AND regis.resultado = res.idresultado AND regis.cedula = '"+search+"' order by regis.fechaExam;")        
            myresult = cur.fetchall()
            if myresult:
                cedula=str(myresult[0][2])
                cur.execute("SELECT gest.fecha 'Fecha Nuevo Ingreso', est.nmestado 'Estado del paciente' FROM covid.registrar regis, covid.gestion gest, covid.estado est WHERE gest.estado= est.idestado and regis.cedula='"+cedula+"' and gest.idcaso=regis.idcaso  order by gest.fecha;")        
                result = cur.fetchall()
                cur.close()
                return render_template("docsearch.html", myresult=myresult, result=result, search=search, select=select,cedula=cedula)
            else:
                return render_template("docsearch.html")
        elif select == "1":
            
            cur.execute("SELECT  regis.nombre, regis.apellido, regis.cedula, sex.nmsexo Sexo, regis.nacimiento 'Fecha Nacimiento', regis.dirCasa 'Dirección Casa', regis.dirTrabajo 'Dirección Trabajo', nmresultado 'Resultado Test Covid', regis.fechaExam 'Fecha de Prueba Covid'FROM covid.registrar regis, covid.sexo sex, covid.resultado res WHERE regis.sexo = sex.idsexo AND regis.resultado = res.idresultado AND regis.idCaso = '"+search+"' order by regis.fechaExam;")        
            myresult = cur.fetchall()
            if myresult:
                cedula=str(myresult[0][2])
                cur.execute("SELECT gest.fecha 'Fecha Nuevo Ingreso', est.nmestado 'Estado del paciente' FROM covid.registrar regis, covid.gestion gest, covid.estado est WHERE gest.estado= est.idestado and regis.cedula='"+cedula+"' and gest.idcaso=regis.idcaso  order by gest.fecha;")        
                result = cur.fetchall()
                cur.execute("SELECT regis.idcaso, gest.fecha 'Fecha Nuevo Ingreso', est.nmestado 'Estado del paciente' FROM covid.registrar regis, covid.gestion gest, covid.estado est WHERE gest.estado= est.idestado and regis.cedula='"+cedula+"' and gest.idcaso=regis.idcaso  order by gest.fecha;")        
                result = cur.fetchall()
                if result:
                    estado=result[len(result)-1][2]
                else:
                    estado=""
                cur.close()

                return render_template("docsearch.html", myresult=myresult, result=result, search=search, select=select,cedula=cedula, estado=estado)
            else:
                    return render_template("docsearch.html",cedula="")

    else:
        return render_template("docsearch.html")

@med.route('/medico/mapa', methods=['POST', 'GET'])
def medico_mapa():
    conn, cur = get_conn()
    cur=conn.cursor()
    cur.execute("SELECT DISTINCT regis.cedula FROM covid.registrar regis;")        
    myresult = cur.fetchall()

    cedulas = []
    for i in range (len(myresult)):
        cedula = str(myresult[i][0])
        cedulas.append(cedula)

    cur.close()   
    return render_template("doc_generalmap.html", cedulas = cedulas)

@med.route('/mapa_general_casos', methods=['POST', 'GET'])
def mapa_general_casos():

    cedula = request.args.get("param1")

    conn, cur = get_conn()
    cur=conn.cursor()
    cur.execute("SELECT regis.latitudCasa, regis.longitudCasa, resul.nmresultado FROM covid.registrar regis, covid.resultado resul where regis.cedula='"+cedula+"' and regis.resultado=resul.idresultado and regis.idCaso = (select MAX(idCaso) FROM covid.registrar regis where regis.cedula='"+cedula+"')")               
    myresult = cur.fetchall()
    

    if myresult[0][2]=="Negativo":
        cur.close()
        return jsonify(myresult)
    else:
        cur.execute("SELECT regis.latitudCasa, regis.longitudCasa, est.nmestado FROM covid.registrar regis, covid.resultado resul, covid.gestion gest, covid.estado est where regis.cedula='"+cedula+"' and regis.resultado=resul.idresultado and regis.cedula=gest.cedula  and regis.idcaso=gest.idcaso and gest.estado=est.idestado and regis.idCaso = (select MAX(regis.idCaso) FROM covid.registrar regis where regis.cedula='"+cedula+"') and est.nmestado = (select est.nmestado FROM covid.estado est, covid.gestion gest, covid.registrar regis where gest.estado=est.idestado  and regis.cedula=gest.cedula  and gest.fecha =(select max(gest.fecha) from covid.gestion gest, covid.registrar regis where regis.cedula='"+cedula+"' and gest.cedula=regis.cedula) and regis.idcaso=gest.idcaso and regis.cedula='"+cedula+"' limit 1)")
        myresult = cur.fetchall()
        if myresult:
            cur.close()
            return jsonify(myresult)
        else:
            cur.execute("SELECT regis.latitudCasa, regis.longitudCasa, resul.nmresultado FROM covid.registrar regis, covid.resultado resul where regis.cedula='"+cedula+"' and regis.resultado=resul.idresultado and regis.idCaso = (select MAX(idCaso) FROM covid.registrar regis where regis.cedula='"+cedula+"')")               
            myresult = cur.fetchall()
            cur.close()
            return jsonify(myresult)

templates/Gesthelper.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="canonical" href="https://aldi.github.io/bulma-login-template/" />
    <title>Gestión de ayudante</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css" />
    <link rel="stylesheet" href="/static/Style.css" />
  </head>
  <body>
   
        <div class="hero-head">
            <nav class="navbar navbar-default" style="background-color: #e6f9ff" role="navigation">
                <div class="navbar-brand">
                  <img src="/static/png/Logo2.png"  width="200" height="30" style="margin-left: 10px" href="Principal.html" >
          
                
                <div class="navbar-burger" aria-level="menu" aria-expanded="false" data-target="navbarExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </div>
                </div>
            
                <div id="navbarExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item has-text-weight-bold" href="{{ url_for('index') }}">
                        Home
                    </a>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary"  href="{{url_for('auth.logout', rol=session['rol'])}}" style="background-color: #003399">
                        Log out
                        </a>
                    </div>
                    </div>
                </div>

            </nav>
        </div>

      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <br>
      <div class="notification is-warning">
          <button class="delete" id="del"></button>
               {{message}}
      </div>
      {% endfor  %}
      {% endif %}
      {% endwith %}

    <section class="hero is-halfheight">
        <div class="hero-body">
            <div class="container">
                <div class="columns">
                    <div class="column is-3">
                        <div class="box">
                          <form action="{{ url_for('helper.manage')}}" method="POST" autocomplete="off">
                            <div class="field">
                              <label class="label is-size-3">Buscar caso</label>
                              <p>
                               Filtre su búsqueda: 
                              </p>
                            </div>
                            <div class="control has-icons-left">
                                <div class="select is-halfwidth">
                                  <select name="select" required>
                                        <option value=""></option>
                                        <option value="1">Case ID</option>
                                        <option value="2">Name</option>
                                        <option value="3">ID (CC)</option>
                                    </select>
                                </div>
                               <span class="icon is-small is-left">
                                <i class="fas fa-id-card-alt"></i>
                                </span>
                            </div>
                            <br>
                            <div class="field">
                                <p class="control has-icons-left">
                                    <input class="input" type="text" placeholder="" name="search" id="search" required>
                                    <span class="icon is-small is-left">
                                    <i class="fas fa-search"></i>
                                    </span>
                                </p>
                            </div>
                            <p class="control"> 
                                <input type="submit" value="Buscar" class="button has-text-weight-bold has-text-white is-medium " style="background-color: #003399">
                              </p><br />
                          </form>
                        </div>
                    </div>
                    <div class="column">
                        <div class="box">
                            <div class="field">
                              <label class="label is-size-3">Datos del caso</label>
                              <table class="table">
                                <thead >
                                  <tr>
                                    <th>Select</th>
                                    <th>IdCaso</th>
                                    <th>Name</th>
                                    <th>Last Name</th>
                                    <th>ID</th>
                                    <th>Gender</th>
                                    <th>Birth</th>
                                    <th>Home Location</th>
                                    <th>Job Location</th>
                                    <th>Result</th>
                                    <th>Date Result</th>
                                  </tr>
                                </thead>
                                {% for row in myresult %}
                                <tbody>
                                  <th class="check">
                                    <input type="checkbox" class="check" id="{{row}}" name="{{row}}">
                                  </th>
                                    {% for cell in row %}
                                    <td>{{cell}}</td>
                                    {% endfor %}
                                    {% endfor %}
                                
                                </tbody>
                                
                              </table>
                            </div>

                            <p class="control">
                              <form action="{{ url_for('helper.manage_add')}}" method="POST" autocomplete="off">
                                <input type="hidden" id="select" name="select" value= "{{select}}" required>
                                <input type="hidden" id="search" name="search" value= "{{search}}" required>
                                <input type="hidden" id="cedula" name="cedula" required>
                                <input type="submit" value="Gestionar" class="button has-text-weight-bold has-text-white is-medium " style="background-color: #003399">
                              </form>
                              </p><br/>
                            
                        </div>
                    </div>
                  </div>
            </div>
        </div>
      <div class="hero-foot">
        <div class="container has-text-centered">
            <p class="footer-text">
                <a  style="color:black;">Designed<!--<i class="fa fa-heart fa-fw" style="font-size: 10px; color: red;"></i>-->
                by </a>
            </p>
        </div>
     </div>
    </section>

  <script src="../static/js/password_hide.js"></script>
    <script>
                function delete_space() {
                    document.getElementById('username').value = document.getElementById('username').value.replace(/\s/g, '');
                };
    </script>
  <script src="../static/js/delete.js"></script>  
        
    
  </body>
</html>

templates/doc_Choices.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Médico</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css" />
    <link rel="stylesheet" href="/static/Style2.css" />
  </head>
  <body>
<section class="hero">
            <div class="hero-head">
                <nav class="navbar navbar-default" style="background-color: #e6f9ff" role="navigation">
                    <div class="navbar-brand">
                    
                        <img src="/static/png/Logo2.png"  width="200" height="30" style="margin-left: 10px;" >
                    
                        <div class="navbar-burger" aria-level="menu" aria-expanded="false" data-target="navbarExample">
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                        </div>
                    </div>
                
                    <div id="navbarExample" class="navbar-menu">
                        <div class="navbar-start">
                          <a class="navbar-item has-text-weight-bold" href="{{ url_for('index') }}">
                            Home
                          </a>
                        </div>
                    </div>   

                    <div class="navbar-end">
                      <div class="navbar-item">
                        <div class="buttons">
                          <a class="button is-primary"  href="{{url_for('auth.logout', rol=session['rol'])}}" style="background-color: #003399">
                            Log out
                          </a>
                        </div>
                      </div>
                    </div>
                </nav>
            </div>
            <div class="hero-body">
                <div class="container">
                    <div class="columns">
                        <div class="column">
                            <div class="box">
                                <div class="field">
                                  <label class="label is-size-3">Búsqueda</label>
                                  <p>
                                    Si usted desea realizar una búsqueda de un paciente en específico presione <b>Continuar</b>  para cargar
                                    la información correspondiente.
                                  </p>
                                </div>
                                <div class="buttons">
                                  <a class="button has-text-weight-bold has-text-white is-medium "  href="{{url_for('med.medico_search')}}" style="background-color: #003399">
                                    Continuar
                                  </a>
                                </div>
                                
                                </div>
                        </div>
                        <div class="column">
                            <div class="box">
                                <div class="field">
                                  <label class="label is-size-3">Mapa general</label>
                                  <p>
                                    Si usted desea visualizar el mapa con la totalidad de casos de COVID-19 de acuerdo su estado
                                    actual presione <b>Continuar</b>. 
                                  </p>
                                </div>
                                <div class="buttons">
                                  <a class="button has-text-weight-bold has-text-white is-medium "  href="{{url_for('med.medico_mapa')}}" style="background-color: #003399">
                                    Continuar
                                  </a>
                                </div>
                                
                                </div>
                        </div>
                      </div>
                </div>
            </div>

  <script src="../static/js/delete.js"></script>   
  </body>
</html>

templates/docsearch.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="canonical" href="https://aldi.github.io/bulma-login-template/" />
    <title>Búsqueda del Médico</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-social@1/bin/bulma-social.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css" />
    <link rel="stylesheet" href="/static/style.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin="" />
  </head>
  <body>
   
        <div class="hero-head">
            <nav class="navbar navbar-default" style="background-color: #e6f9ff" role="navigation">
                <div class="navbar-brand">
                    <img src="/static/png/Logo2.png"  width="200" height="30" style="margin-left: 10px" href="Principal.html" >
                
                <div class="navbar-burger" aria-level="menu" aria-expanded="false" data-target="navbarExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </div>
                </div>
            
                <div id="navbarExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item has-text-weight-bold" href="{{ url_for('index') }}">
                        Home
                    </a>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary"  href="{{url_for('auth.logout', rol=session['rol'])}}" style="background-color: #003399">
                        Log out
                        </a>
                    </div>
                    </div>
                </div>

            </nav>
        </div>

    <section class="hero is-halfheight">
        <div class="hero-body">
            <div class="container">
               
                <input class="input" type="hidden" placeholder="" name="buscar" id="buscar" value={{cedula}} required>
                <input class="input" type="hidden" placeholder="" name="estado" id="estado" value={{estado}} required>

                <div class="columns">   
                   <div class="column is-3">
                        <div class="box">
                            <form action="{{ url_for('med.medico_search')}}" method="POST" autocomplete="off">
                                 <div class="field">
                                    <label class="label is-size-3">Buscar caso</label>
                                        <p>
                                            Filtre su búsqueda: 
                                        </p>
                                </div>
                                <div class="control has-icons-left">
                                    <div class="select is-halfwidth">
                                        <select name="select" required>
                                            <option value=""></option>
                                            <option value="1">Case ID</option>
                                            <option value="2">ID (CC)</option>
                                        </select>
                                    </div>
                                    <span class="icon is-small is-left">
                                        <i class="fas fa-id-card-alt"></i>
                                        </span>
                                </div>
                        <br>
                                <div class="field">
                                    <p class="control has-icons-left">
                                        <input class="input" type="text" placeholder="" name="search" id="search" required>
                                        <span class="icon is-small is-left">
                                        <i class="fas fa-search"></i>
                                        </span>
                                    </p>
                                </div>
                                <p class="control"> 
                                    <input type="submit" value="Buscar" class="button has-text-weight-bold has-text-white is-medium " id="buscar" style="background-color: #003399">
                                </p><br>
                             </form>     
                        </div>
                    </div>
                    <div class="column is-4">
                        <div class="box">
                          <form action="{{ url_for('med.medico_search')}}" method="POST" autocomplete="off">
                            <div class="field">
                                <label class="label is-size-3">Estados</label>
                                <table class="table is is-halfwidth">
                                  <thead >
                                    <tr>
                                      <th>IdCaso</th>
                                      <th>Fecha de Ingreso</th>
                                      <th>Estado del paciente</th>
                                      
                                      
                                    </tr>
                                  </thead>
                                  
                                  <tbody>
                                    <tr>
                                        {% for row in result %}
                                        <tbody>
                                            {% for cell in row %}
                                            <td>{{cell}}</td>
                                            {% endfor %}
                                            {% endfor %}
                                    </tr>
                                    <tr>

                                    </tr>
                                  </tbody>
                                </table>
                              </div>
                              </form>
                            </div>
                          </div>
                 </div>
                 <div class="columns">
                    <div class="column">
                        <div class="box">
                            <div class="field">
                              <label class="label is-size-3">Datos del paciente</label>
                              <table class="table is is-fullwidth">
                                <thead >
                                  <tr>
                                    
                                    <th>Name</th>
                                    <th>Last Name</th>
                                    <th>ID</th>
                                    <th>Gender</th>
                                    <th>Birth</th>
                                    <th>Home Location</th>
                                    <th>Job Location</th>
                                    <th>Result</th>
                                    <th>Date Result</th>
                                  </tr>
                                </thead>
                                
                                {% for row in myresult %}
                                <tbody>
                                    {% for cell in row %}
                                    <td>{{cell}}</td>
                                    {% endfor %}
                                    {% endfor %}
                                
                                </tbody>
                              </table>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="columns">
                     <div class="column">
                         <div class="box">
                            <div id="CovidMap" class="mapa"></div>
                         </div>
                     </div>
                 </div>
            
            </div>
        </div>
        
      <div class="hero-foot">
        <div class="container has-text-centered">
            <p class="footer-text">
                <a  style="color:black;">Designed<!--<i class="fa fa-heart fa-fw" style="font-size: 10px; color: red;"></i>-->
                by Saray Cortez, Mariana Cabarcas Vecino, Maria Jose Morales y Jesús Suarez </a>
            </p>
        </div>
     </div>
    </section>

            <script src="/static/js/delete.js"></script>  
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin="">
    </script>
    <script src="/static/js/map.js"></script>

  </body>
</html>